{{- if .Values.apiServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow-pipelines.fullname" . }}-api-server
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
  - port: {{ .Values.apiServer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: 8887
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "kubeflow-pipelines.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
{{- end }}
