{{- if not .Values.apiServer.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow-pipelines.fullname" . }}-db
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "kubeflow" | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
---
{{- if not .Values.apiServer.objectStore.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow-pipelines.fullname" . }}-minio
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ "minioadmin" | b64enc | quote }}
  secretKey: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
