{{- if not .Values.backend.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-postgresql
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "mlflow" | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
---
{{- if and (eq .Values.backend.artifactStore.type "s3") (not .Values.backend.artifactStore.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-s3
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.artifactStore.s3.accessKeyId }}
  accessKeyId: {{ .Values.backend.artifactStore.s3.accessKeyId | b64enc | quote }}
  {{- else }}
  accessKeyId: {{ "minioadmin" | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.artifactStore.s3.secretAccessKey }}
  secretAccessKey: {{ .Values.backend.artifactStore.s3.secretAccessKey | b64enc | quote }}
  {{- else }}
  secretAccessKey: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
