apiVersion: v1
kind: Service
metadata:
  name: {{ include "janusgraph.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "janusgraph.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gremlin
      protocol: TCP
      name: gremlin
  selector:
    {{- include "janusgraph.selectorLabels" . | nindent 4 }}
