apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
  username: {{ .Values.auth.username | quote }}
  database: {{ .Values.auth.database | quote }}
