apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
      protocol: TCP
    - name: external
      port: {{ .Values.service.ports.external }}
      targetPort: external
      protocol: TCP
    - name: controller
      port: {{ .Values.service.ports.controller }}
      targetPort: controller
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
