suite_name: default_bronze
layer: bronze
description: Default quality expectations for Bronze layer (raw ingestion)

expectations:
  - expectation_type: expect_table_row_count_to_be_between
    kwargs:
      min_value: 1

  - expectation_type: expect_column_values_to_not_be_null
    kwargs:
      column: id

  - expectation_type: expect_column_values_to_be_of_type
    kwargs:
      column: id
      type_: string
