{{- if .Values.featureServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "feast.fullname" . }}-feature-server
  labels:
    {{- include "feast.labels" . | nindent 4 }}
    app.kubernetes.io/component: feature-server
spec:
  type: {{ .Values.featureServer.service.type }}
  ports:
  - port: {{ .Values.featureServer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.monitoring.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "feast.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: feature-server
{{- end }}
