apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "couchdb.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
data:
  custom.ini: |
    {{- range $section, $config := .Values.couchdbConfig }}
    [{{ $section }}]
    {{- range $key, $value := $config }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}
