apiVersion: v1
kind: Secret
metadata:
  name: {{ include "couchdb.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
type: Opaque
data:
  adminPassword: {{ .Values.adminPassword | b64enc | quote }}
  cookieAuthSecret: {{ randAlphaNum 64 | b64enc | quote }}
